apiVersion: v1
kind: Pod
metadata: 
  name: webapp
  labels: 
    app: webapp
    release: "0"
spec:
  containers:
  -  name: webapp
     image: richardchesterwood/k8s-fleetman-webapp-angular:release0

---
#3 dashes to define second pod
apiVersion: v1
kind: Pod
metadata: 
  name: webappv2
  labels: 
    app: webapp
    release: "0-5"
spec:
  containers:
  -  name: webapp
     image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---
apiVersion: v1
kind: Pod
metadata: 
  name: queue1
  labels: 
    app: queue1
spec:
  containers:
  -  name: queue1
     image: richardchesterwood/k8s-fleetman-queue:release1
