kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: fleetman-webapp
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
    #accept traffic on port 80 from service
      port: 80
      #forward traffic to port 80 on containe
      targetPort: 80
      nodePort: 30080
      #port available to browser >30000
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector. This selector will select all pods with key app and alue webapp
    app: webapp
  type: NodePort 
  # available to whole Kubernetes cluster, expose a port through this node.
---

kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: fleetman-queue
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
    #accept traffic on port 80 from service
      port: 8161
      #forward traffic to port 80 on containe
#      targetPort: 8161
      nodePort: 30010
      #port available to browser >30000
  selector:
    app: queue1
  type: NodePort